export IMAGE_FAMILY="pytorch-1-0-cu92-experimental"
export ZONE="us-west1-b"
export INSTANCE_NAME="ankit-pytorch"
export PROJECT="formal-platform-162818"
export INSTANCE_SPEC="type=nvidia-tesla-v100,count=1"
